### ISSUE TITLE
vivians damage

### ISSUE THREAD

**Issue by PropaPanda6** [tyopoyt/epic7-damage-calc#130] opened 2023-09-12 16:58 UTC
green vivians damage seems to be off by atleast an extra zero. i dont know if the multipliers are wrong but my 3.3k atk 292 cdmg vivians apparently doing 521 dmg to the banshee 13 wave. no gab, just atk buff. in game im doing over 5k

**Comment by tyopoyt** [comment] 2023-09-14 14:23
Will look into this, thanks

**Comment by tyopoyt** [comment] 2023-09-17 19:19
Would you be able to provide screenshots or, preferably, a link to the settings that cause this behavior?  I plugged in 3300 attack, 292 crit damage, attack buff, elemental advantage and one of the two b13 wave 1 units (they both have the same stats) and am getting normal-looking results.  I don't see a low number like 500: https://e7calc.xyz/index.html?hero=vivian&atkUp=true&defPreset=mystychain-13&oneshot=11015&atk=3300&crit=292&elemAdv=true

If you press the green share button in the damage section it should copy a link to your clipboard with all the settings filled out

**Comment by tyopoyt** [comment] 2023-10-03 21:29
@PropaPanda6 Without more info I'll probably close this next week as I can't reproduce

**Comment by tyopoyt** [comment] 2023-10-09 20:48
Closing due to inactivity, feel free to reopen an issue with some more details if the behavior persists.

**Closed by tyopoyt** 2023-10-09 20:48 UTC
